### ISSUE TITLE
Implement functions that return DataFrame objects for various components

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#12]
For example, a function like `get_node_dataframe(wm, wntr, node_id)` could return a DataFrame object that describes the evolution of a node's properties over time. I would suggest keeping the mapping of the returned WNTR component data as consistent with the WaterModels network structure as possible. Here are some propositions for what I think the columns of each component DataFrame object could look like. Of course, we can also discuss alternative data structures if you don't think this looks right:

Nodes:
- time
- elevation
- head_wntr
- head_watermodels
- pressure_wntr
- pressure_watermodels

Tanks:
- time
- volume_wntr
- volume_watermodels
- level_wntr (i.e., head minus bottom elevation)
- level_watermodels

Pipes:
- time
- flow_wntr
- flow_watermodels

Short Pipes:
- time
- flow_wntr
- flow_watermodels

Valves:
- time
- flow_wntr (should presumably copy the values from the associated pipes)
- flow_watermodels

Pumps:
- time
- status
- flow_wntr
- flow_watermodels
- head_gain_wntr
- head_gain_watermodels
- cost_wntr
- cost_watermodels
- power_wntr
- power_watermodels

**Comment by enzoliuyang94** [comment]
@tasseff Thanks! Will work on it.

**Comment by jjstickel** [comment]
@enzoliuyang94 , the usual practice is to not close issues until merged with master. Please create a PR with your branch and give me or Byron a chance to review it.

**Comment by enzoliuyang94** [comment]
@jjstickel My bad. Will do so now. Thanks for letting me know the standard work flow.
