### ISSUE TITLE
Remove print statements that are called during a simulation

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#17]
For example, `----- WNTR Simulation Completed -----` is produced on every simulation run, which results in verbosity during the execution an iterative algorithm.

**Comment by jjstickel** [comment]
@enzoliuyang94 , please make a pull request to master (or merge directly, if trivial changes) before closing tickets.

**Comment by enzoliuyang94** [comment]
@jjstickel My bad, I thought this was a rather trivial issue so I just made the change and closed issue. Will do exactly what you suggest in the future regarding the use of Github.

**Comment by jjstickel** [comment]
Please go ahead and make a PR now. Adding "closes #17" in the description of the PR should automatically close this issue when the PR is merged.
