### ISSUE TITLE
Resolve Python warnings

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#18]
When running the simulation routine, I observe the following Python warnings
```bash
┌ Warning: `getindex(o::PyObject, s::AbstractString)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o."s"` instead of `o["s"]`.
│   caller = get_node_dataframe(::Dict{String,Any}, ::Dict{String,Any}, ::PyCall.PyObject, ::PyCall.PyObject, ::String) at validation.jl:37
```
Can this be updated according to the warning so that these warnings are not produced?

**Comment by enzoliuyang94** [comment]
@tasseff I couldn't replicate this error, even after I update my PyCall. The line was 

'head_wntr[t] = wntr_simulation.node["head"][node_name].values[t]'

and changing [node_name] to .node_name or ["head"] to ."head" would not work.

**Comment by tasseff** [comment]
Interesting, I played around with this and could also not get it to work. I will do some more investigation. Out of curiosity, which version of PyCall do you have installed? I'm using v1.92.1.

**Comment by jjstickel** [comment]
I don't see this error either. I have PyCall v1.91.4. Not sure why it won't upgrade to 1.92.1---must be I have some other package (PyPlot?) that has the version pinned.

**Comment by enzoliuyang94** [comment]
@tasseff My PyCall version is v1.91.4 as well. As Jonathan said, I did upgrade PyCall but it doesn't upgrade to v1.92.1.

**Comment by tasseff** [comment]
Oh, I think you have to update your Project.toml to accomodate v1.92. I did this locally.

**Comment by jjstickel** [comment]
Why have a version specified for PyCall in Project.toml? Unless there is breakage expected for new versions coming along, I would rather just not have packages listed in the `[compat]` section at all. So, I suggest we remove the entries for ColorSchemes, ColorTypes, Memento, Plots, PyCall, and DataFrames (leaving only WaterModels and julia).

**Comment by tasseff** [comment]
@jjstickel Read [this](https://github.com/JuliaRegistries/General/blob/master/README.md#automatic-merging-of-pull-requests). These are requirements for automatically registering a new version of your package with the Julia registry.

**Comment by jjstickel** [comment]
OIC. Can we do this when we actually want WMA to be registered? Until then, I just find these things a hassle. Julia's package and version system is a PITA, in my opinion.

**Comment by tasseff** [comment]
It's certainly possible that a future version of a package dependency will end up breaking WaterModelsAnalytics if upper version bounds are not specified in `compat`. An example could be, once v1.93 of PyCall gets released, the warning I posted in this issue could instead turn into an error since the access method may become fully deprecated and removed from PyCall. I don't think there's too much to do aside from specifying the newer version of PyCall in Project.toml. I can submit a pull request with that change, if you'd like.

**Comment by jjstickel** [comment]
I get all that. But while in active alpha development, I suggest we don't
put compat lines and always target latest package releases. This currently
means 1.92 for PyCall, but if breaking changes happen in 1.93, then we make
the necessary fixes.

**Comment by tasseff** [comment]
Ultimately, this is up to you, and I'm just providing suggestions. If you are concerned about keeping `compat`, up-to-date, Julia does have [CompatHelper](https://github.com/JuliaRegistries/CompatHelper.jl), which automatically opens pull requests that modify `Project.toml` to reflect more recent package dependencies (when they're released) while also ensuring the suggested packages do not result in test failure. I think specifying package dependencies is good practice even if development is done locally, but I also understand if you feel that it entails too much overhead for the time being.

**Comment by jjstickel** [comment]
@tasseff , I think your PR resolved this issue?

**Comment by tasseff** [comment]
@jjstickel No, it's still unresolved (on my machine, anyway). I spent around an hour trying to fix the syntax, but the syntax they suggest does not work (like Yang said).

**Comment by jjstickel** [comment]
I'll take a look when I get a chance. I have resolved similar warnings with PyCall.
