### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#21]
This should document changes across future versions. See, for example, [this one](https://github.com/lanl-ansi/WaterModels.jl/blob/master/CHANGELOG.md).

**Comment by jjstickel** [comment]
@tasseff , do you have an automated way to generate the list of changes between versions?

**Comment by tasseff** [comment]
I believe Julia's TagBot will automatically generate a list of closed issues and append them as details on each version release. However, that's separate from a typical CHANGELOG, which is manually edited for each version and describes the major changes made for that version.

**Comment by jjstickel** [comment]
Changelog was created with 5e12c1a3efb9fe9360f426925718e2cad2eb7ca5
