### ISSUE TITLE
create WNTR/EPANET network from WaterModels network

### ISSUE THREAD

**Issue by jjstickel** [NREL-SIIP/WaterModelsAnalytics.jl#27]
Rather reading the network and modifying it, create the WNTR network directly from the WM object.

**Comment by jjstickel** [comment]
@enzoliuyang94 , your merged PR closes this, right?

**Comment by enzoliuyang94** [comment]
> @enzoliuyang94 , your merged PR closes this, right?

@jjstickel Yes, I merged after our Thursday meeting.

**Comment by jjstickel** [comment]
Closed with PR #31
