### ISSUE TITLE
Fix WNTR errors that arise when simulating `Richmond_skeleton`

### ISSUE THREAD

**Issue by tasseff** [NREL-SIIP/WaterModelsAnalytics.jl#29]
I am seeing the following errors when trying to use the `simulate` function on the `Richmond_skeleton` network:

```bash
       WaterModelsAnalytics.simulate(wm.data, result, network_path);
/Users/btasseff/Library/Python/3.8/lib/python/site-packages/wntr/epanet/io.py:2173: UserWarning: Not all curves were used in "examples/data/epanet/Richmond_skeleton.inp"; added with type None, units conversion left to user
  warnings.warn('Not all curves were used in "{}"; added with type None, units conversion left to user'.format(self.wn.name))
ERROR: PyError ($(Expr(:escape, :(ccall(#= /Users/btasseff/.julia/packages/PyCall/BcTLp/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'ValueError'>
ValueError('Shape of passed values is (1543, 1), indices imply (768, 25)')
  File "/Users/btasseff/Library/Python/3.8/lib/python/site-packages/wntr/sim/epanet.py", line 118, in run_sim
    return self.reader.read(outfile)
  File "/Users/btasseff/Library/Python/3.8/lib/python/site-packages/wntr/epanet/io.py", line 2880, in read
    df = pd.DataFrame(data.transpose(), index =index, columns = reporttimes)
  File "/Users/btasseff/Library/Python/3.8/lib/python/site-packages/pandas/core/frame.py", line 497, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/Users/btasseff/Library/Python/3.8/lib/python/site-packages/pandas/core/internals/construction.py", line 234, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/Users/btasseff/Library/Python/3.8/lib/python/site-packages/pandas/core/internals/managers.py", line 1672, in create_block_manager_from_blocks
    raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
```

Below is a small script that solves a continuously relaxed OWF problem, then simulates the result. I used this to produce the errors above:

```julia
import Gurobi
import Ipopt
import JuMP
import WaterModels
const WM = WaterModels

using Revise
using WaterModelsAnalytics

network_path = "examples/data/epanet/Richmond_skeleton.inp";
network = WM.parse_file(network_path);
network_mn = WM.make_multinetwork(network);

ext = Dict(:pipe_breakpoints => 5, :pump_breakpoints => 5);
wm = WM.instantiate_model(network_mn, WM.LRDWaterModel, WM.build_mn_owf; ext = ext);
WM.relax_all_binary_variables!(wm);

# Set the optimizer and other important solver parameters.
WM.JuMP.set_optimizer(wm.model, Gurobi.Optimizer);
WM._MOI.set(wm.model, WM._MOI.NumberOfThreads(), 1);

# Solve the OWF optimization problem.
result = WM.optimize_model!(wm);

# Run a simulation.
WaterModelsAnalytics.simulate(wm.data, result, network_path);
```

**Comment by enzoliuyang94** [comment]
@tasseff  Are you simulating an optimized pumping schedule? I definitely have encountered this type of error before when developing heuristic algorithms to solve the pump scheduling problem, as far as I can recall, this error typically implies that the enforced pumping schedule is not feasible and the simulation fails.

If this is a non-optimized pumping schedule you are trying to simulate during the process of optimization, I think the most reasonable thing to do is to catch this error.

**Comment by tasseff** [comment]
Inspired by the issue posted [here](https://github.com/USEPA/WNTR/issues/94), I experimented a bit more with the numerical parameters listed [here](http://wateranalytics.org/EPANET/_options_page.html). In this specific case, changing `Accuracy` from 0.001 to 0.01 resolved the issue. However, I'm not sure it's always true that this error implies infeasibility. From what it sounds like, it implies numerical instability within the EPANET solver while trying to reach a solution.

**Comment by tasseff** [comment]
Another option, not related to accuracy, seems to be modifying `Unbalanced Stop` to `Unbalanced Continue 100`. I'm not sure if we should deal with these numerical issues programmatically within WaterModelsAnalytics. However, I agree that it would be useful for WaterModelsAnalytics to catch this error.

**Comment by tasseff** [comment]
I think I can close this since explicitly setting different numerical settings seem to resolve this.
