### ISSUE TITLE
does `update_wntr_controls()` work?

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL-SIIP/WaterModelsAnalytics.jl#37]
When I run a pump optimization with WM, and then call:
```
WMA.update_wntr_controls(wntr_data, w_data, result_owf["solution"], 30.0)
wntr_result_owf = WMA.simulate_wntr(wntr_data)
```
 
What should I expect to see? 
I get a result where all the pumps are off, but I was expecting to see a pattern similar to the one in result_owf.

Also, *nit* since this function is modifying the values in `wntr_data` it should be named `update_wntr_controls!()`

**Comment by tasseff** [comment]
I will take a look at correcting this function as soon as possible.

**Comment by tasseff** [comment]
@claytonpbarrows, aside from some corrections for WaterModels v0.6 on the `wm-v0.6` branch, I've also placed an example that optimizes the Van Zyl problem using WaterModels, then simulates it using WaterModelsAnalytics, in `scripts/wm_optimization-wma_simulation.jl` of PowerWaterExamples. Inspecting the pump dataframes that are generated by this script, I am finding that the pump statuses match. Maybe the problem you're seeing is related to the specific data that you're passing into the `update_wntr_controls` function?

**Comment by claytonpbarrows** [comment]
I think this was an issue with using the wrong versions, etc...
